FROM arxiv/base:0.14.3

WORKDIR /opt/arxiv/

# Install MySQL.
RUN yum install -y which mysql mysql-devel
RUN yum install autoconf libcurl-devel expat-devel gcc gettext-devel kernel-headers openssl-devel perl-devel zlib-devel make -y
RUN curl -O -L https://github.com/git/git/archive/v2.20.1.tar.gz
RUN tar -zxvf v2.20.1.tar.gz
RUN ls -la /opt/arxiv

WORKDIR /opt/arxiv/git-2.20.1
RUN ls -la /opt/arxiv/git-2.20.1
RUN make configure && ./configure --prefix=/usr && make all && make install
