"""Category and archive definitions."""
from typing import Dict
from datetime import date

from arxiv.taxonomy.category import Group, Archive, Category

"""
arXiv group, archive and category definitions.

arXiv categories are arranged in a hierarchy where there are archives
(astro-ph, cs, math, etc.) that contain subject classes (astro-ph has subject
classes CO, GA, etc.). We now use the term category to refer to any archive or
archive.subject_class that one can submit to (so hep-th and math.IT are both
categories). No subject class can be in more than one archive. However, our
scientific advisors identify some categories that should appear in more than
one archive because they bridge major subject areas. Examples include math.MP
== math-ph and stat.TH = math.ST. These are called category aliases and the
idea is that any article classified in one of the aliases categories also
appears in the other (canonical), but that most of the arXiv code for display,
search, etc. does not need to understand the break with hierarchy.

"""

#GROUP DATA
GROUPS: Dict[str, Group] = {
    "grp_physics":Group(
            id="grp_physics",
            full_name="Physics",
            is_active=True,
            start_year=1991,
            default_archive="hep-th",
            ),
    "grp_math":Group(
            id="grp_math",
            full_name="Mathematics",
            is_active=True,
            start_year=1992,
            default_archive="math",
            ),
    "grp_q-bio":Group(
            id="grp_q-bio",
            full_name="Quantitative Biology",
            is_active=True,
            start_year=1992,
            default_archive="q-bio",
            ),
    "grp_cs":Group(
            id="grp_cs",
            full_name="Computer Science",
            is_active=True,
            start_year=1993,
            default_archive="cs",
            ),
    "grp_test":Group(
            id="grp_test",
            full_name="Test",
            is_active=True,
            start_year=1995,
            is_test=True
            ),
    "grp_q-fin":Group(
            id="grp_q-fin",
            full_name="Quantitative Finance",
            is_active=True,
            start_year=1997,
            ),
    "grp_stat":Group(
            id="grp_stat",
            full_name="Statistics",
            is_active=True,
            start_year=1999,
            ),
    "grp_eess":Group(
            id="grp_eess",
            full_name="Electrical Engineering and Systems Science",
            is_active=True,
            start_year=2017,
            ),
    "grp_econ":Group(
            id="grp_econ",
            full_name="Economics",
            is_active=True,
            start_year=2017,
            )
}

#ARCHIVE DATA
ARCHIVES: Dict[str, Archive]= {
    "acc-phys":Archive(
        id="acc-phys",
        full_name="Accelerator Physics",
        is_active=False,
        alt_name="physics.acc-ph",
        in_group="grp_physics",
        start_date=date(1994, 11, 1),
        end_date=date(1996, 9, 1),
        ),
    "adap-org":Archive(
            id="adap-org",
            full_name="Adaptation, Noise, and Self-Organizing Systems",
            is_active=False,
            alt_name="nlin.AO",
            in_group="grp_physics",
            start_date=date(1993, 3, 1),
            end_date=date(1999, 12, 1),
            ),
    "alg-geom":Archive(
            id="alg-geom",
            full_name="Algebraic Geometry",
            is_active=False,
            alt_name="math.AG",
            in_group="grp_math",
            start_date=date(1992, 2, 1),
            end_date=date(1997, 12, 1),
            ),
    "ao-sci":Archive(
            id="ao-sci",
            full_name="Atmospheric-Oceanic Sciences",
            is_active=False,
            alt_name="physics.ao-ph",
            in_group="grp_physics",
            start_date=date(1995, 2, 1),
            end_date=date(1996, 9, 1),
            ),
    "astro-ph":Archive(
            id="astro-ph",
            full_name="Astrophysics",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1992, 4, 1),
            ),
    "atom-ph":Archive(
            id="atom-ph",
            full_name="Atomic, Molecular and Optical Physics",
            is_active=False,
            alt_name="physics.atom-ph",
            in_group="grp_physics",
            start_date=date(1995, 9, 1),
            end_date=date(1996, 9, 1),
            ),
    "bayes-an":Archive(
            id="bayes-an",
            full_name="Bayesian Analysis",
            is_active=False,
            alt_name="physics.data-an",
            in_group="grp_physics",
            start_date=date(1995, 6, 1),
            end_date=date(1996, 11, 1),
            ),
    "chao-dyn":Archive(
            id="chao-dyn",
            full_name="Chaotic Dynamics",
            is_active=False,
            alt_name="nlin.CD",
            in_group="grp_physics",
            start_date=date(1993, 1, 1),
            end_date=date(1999, 12, 1),
            ),
    "chem-ph":Archive(
            id="chem-ph",
            full_name="Chemical Physics",
            is_active=False,
            alt_name="physics.chem-ph",
            in_group="grp_physics",
            start_date=date(1994, 3, 1),
            end_date=date(1996, 9, 1),
            ),
    "cmp-lg":Archive(
            id="cmp-lg",
            full_name="Computation and Language",
            is_active=False,
            alt_name="cs.CL",
            in_group="grp_cs",
            start_date=date(1994, 4, 1),
            end_date=date(1998, 9, 1),
            ),
    "comp-gas":Archive(
            id="comp-gas",
            full_name="Cellular Automata and Lattice Gases",
            is_active=False,
            alt_name="nlin.CG",
            in_group="grp_physics",
            start_date=date(1993, 2, 1),
            end_date=date(1999, 12, 1),
            ),
    "cond-mat":Archive(
            id="cond-mat",
            full_name="Condensed Matter",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1992, 4, 1),
            ),
    "cs":Archive(
            id="cs",
            full_name="Computer Science",
            is_active=True,
            in_group="grp_cs",
            start_date=date(1993, 1, 1),
            ),
    "dg-ga":Archive(
            id="dg-ga",
            full_name="Differential Geometry",
            is_active=False,
            alt_name="math.DG",
            in_group="grp_math",
            start_date=date(1994, 6, 1),
            end_date=date(1997, 12, 1),
            ),
    "econ":Archive(
            id="econ",
            full_name="Economics",
            is_active=True,
            in_group="grp_econ",
            start_date=date(2017, 9, 1),
            ),
    "eess":Archive(
            id="eess",
            full_name="Electrical Engineering and Systems Science",
            is_active=True,
            in_group="grp_eess",
            start_date=date(2017, 9, 1),
            ),
    "funct-an":Archive(
            id="funct-an",
            full_name="Functional Analysis",
            is_active=False,
            alt_name="math.FA",
            in_group="grp_math",
            start_date=date(1992, 4, 1),
            end_date=date(1997, 12, 1),
            ),
    "gr-qc":Archive(
            id="gr-qc",
            full_name="General Relativity and Quantum Cosmology",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1992, 7, 1),
            ),
    "hep-ex":Archive(
            id="hep-ex",
            full_name="High Energy Physics - Experiment",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1994, 4, 1),
            ),
    "hep-lat":Archive(
            id="hep-lat",
            full_name="High Energy Physics - Lattice",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1992, 2, 1),
            ),
    "hep-ph":Archive(
            id="hep-ph",
            full_name="High Energy Physics - Phenomenology",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1992, 3, 1),
            ),
    "hep-th":Archive(
            id="hep-th",
            full_name="High Energy Physics - Theory",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1991, 8, 1),
            ),
    "math":Archive(
            id="math",
            full_name="Mathematics",
            is_active=True,
            in_group="grp_math",
            start_date=date(1992, 2, 1),
            ),
    "math-ph":Archive(
            id="math-ph",
            full_name="Mathematical Physics",
            is_active=True,
            alt_name="math.MP",
            in_group="grp_physics",
            start_date=date(1996, 9, 1),
            ),
    "mtrl-th":Archive(
            id="mtrl-th",
            full_name="Materials Theory",
            is_active=False,
            alt_name="cond-mat.mtrl-sci",
            in_group="grp_physics",
            start_date=date(1994, 11, 1),
            end_date=date(1996, 9, 1),
            ),
    "nlin":Archive(
            id="nlin",
            full_name="Nonlinear Sciences",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1993, 1, 1),
            ),
    "nucl-ex":Archive(
            id="nucl-ex",
            full_name="Nuclear Experiment",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1994, 12, 1),
            ),
    "nucl-th":Archive(
            id="nucl-th",
            full_name="Nuclear Theory",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1992, 10, 1),
            ),
    "patt-sol":Archive(
            id="patt-sol",
            full_name="Pattern Formation and Solitons",
            is_active=False,
            alt_name="nlin.PS",
            in_group="grp_physics",
            start_date=date(1993, 2, 1),
            end_date=date(1999, 12, 1),
            ),
    "physics":Archive(
            id="physics",
            full_name="Physics",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1996, 10, 1),
            ),
    "plasm-ph":Archive(
            id="plasm-ph",
            full_name="Plasma Physics",
            is_active=False,
            alt_name="physics.plasm-ph",
            in_group="grp_physics",
            start_date=date(1995, 9, 1),
            end_date=date(1996, 9, 1),
            ),
    "q-alg":Archive(
            id="q-alg",
            full_name="Quantum Algebra and Topology",
            is_active=False,
            alt_name="math.QA",
            in_group="grp_math",
            start_date=date(1994, 12, 1),
            end_date=date(1997, 12, 1),
            ),
    "q-bio":Archive(
            id="q-bio",
            full_name="Quantitative Biology",
            is_active=True,
            in_group="grp_q-bio",
            start_date=date(2003, 9, 1),
            ),
    "q-fin":Archive(
            id="q-fin",
            full_name="Quantitative Finance",
            is_active=True,
            in_group="grp_q-fin",
            start_date=date(2008, 12, 1),
            ),
    "quant-ph":Archive(
            id="quant-ph",
            full_name="Quantum Physics",
            is_active=True,
            in_group="grp_physics",
            start_date=date(1994, 12, 1),
            ),
    "solv-int":Archive(
            id="solv-int",
            full_name="Exactly Solvable and Integrable Systems",
            is_active=False,
            alt_name="nlin.SI",
            in_group="grp_physics",
            start_date=date(1993, 4, 1),
            end_date=date(1999, 12, 1),
            ),
    "stat":Archive(
            id="stat",
            full_name="Statistics",
            is_active=True,
            in_group="grp_stat",
            start_date=date(2007, 4, 1),
            ),
    "supr-con":Archive(
            id="supr-con",
            full_name="Superconductivity",
            is_active=False,
            alt_name="cond-mat.supr-con",
            in_group="grp_physics",
            start_date=date(1994, 11, 1),
            end_date=date(1996, 9, 1),
            ),
    "test":Archive(
            id="test",
            full_name="Test",
            is_active=True,
            in_group="grp_test",
            start_date=date(1995, 2, 1),
            )
}

ARCHIVES_ACTIVE = {key: arch for key,
                   arch in ARCHIVES.items()
                   if arch.is_active}

# defunct archives subsumed by categories
ARCHIVES_SUBSUMED: Dict[str, str] = {
    'cmp-lg': 'cs.CL',
    'adap-org': 'nlin.AO',
    'comp-gas': 'nlin.CG',
    'chao-dyn': 'nlin.CD',
    'solv-int': 'nlin.SI',
    'patt-sol': 'nlin.PS',
    'alg-geom': 'math.AG',
    'dg-ga': 'math.DG',
    'funct-an': 'math.FA',
    'q-alg': 'math.QA',
    'mtrl-th': 'cond-mat.mtrl-sci',
    'supr-con': 'cond-mat.supr-con',
    'acc-phys': 'physics.acc-ph',
    'ao-sci': 'physics.ao-ph',
    'atom-ph': 'physics.atom-ph',
    'bayes-an': 'physics.data-an',
    'chem-ph': 'physics.chem-ph',
    'plasm-ph': 'physics.plasm-ph'
}

# Legacy bare-archive names used as primary and secondary
# categories for old submissions. yyyy-mm is last month allowed.
LEGACY_ARCHIVE_AS_PRIMARY: Dict[str, date] = {
    'astro-ph': date(2008, 12, 1),
    'cond-mat': date(2004, 1, 1),
    'test': date(2010, 1, 1)
}
LEGACY_ARCHIVE_AS_SECONDARY = {
    'astro-ph': date(2008, 12, 1),
    'cond-mat': date(2004, 1, 1),
    'q-bio': date(2003, 8, 1),
    'test': date(2010, 1, 1)
}

#CATEGORY DATA
CATEGORIES: Dict[str, Category] = {
        "acc-phys": Category(
            id="acc-phys",
            full_name="Accelerator Physics",
            is_active=False,
            alt_name="physics.acc-ph",
            in_archive="acc-phys",
            is_general=False,
            ),
    "adap-org": Category(
            id="adap-org",
            full_name="Adaptation, Noise, and Self-Organizing Systems",
            alt_name="nlin.AO",
            is_active=False,
            in_archive="adap-org",
            is_general=False,
            ),
    "alg-geom": Category(
            id="alg-geom",
            full_name="Algebraic Geometry",
            is_active=False,
            alt_name="math.AG",
            in_archive="alg-geom",
            is_general=False,
            ),
    "ao-sci": Category(
            id="ao-sci",
            full_name="Atmospheric-Oceanic Sciences",
            is_active=False,
            alt_name="physics.ao-ph",
            in_archive="ao-sci",
            is_general=False,
            ),
    "astro-ph": Category(
            id="astro-ph",
            full_name="Astrophysics",
            is_active=False,
            in_archive="astro-ph",
            is_general=False,
            ),
    "astro-ph.CO": Category(
            id="astro-ph.CO",
            full_name="Cosmology and Nongalactic Astrophysics",
            is_active=True,
            in_archive="astro-ph",
            is_general=False,
            description="Phenomenology of early universe, cosmic microwave background, cosmological parameters, primordial element abundances, extragalactic distance scale, large-scale structure of the universe. Groups, superclusters, voids, intergalactic medium. Particle astrophysics: dark energy, dark matter, baryogenesis, leptogenesis, inflationary models, reheating, monopoles, WIMPs, cosmic strings, primordial black holes, cosmological gravitational radiation",
            ),
    "astro-ph.EP": Category(
            id="astro-ph.EP",
            full_name="Earth and Planetary Astrophysics",
            is_active=True,
            in_archive="astro-ph",
            is_general=False,
            description="Interplanetary medium, planetary physics, planetary astrobiology, extrasolar planets, comets, asteroids, meteorites. Structure and formation of the solar system",
            ),
    "astro-ph.GA": Category(
            id="astro-ph.GA",
            full_name="Astrophysics of Galaxies",
            is_active=True,
            in_archive="astro-ph",
            is_general=False,
            description="Phenomena pertaining to galaxies or the Milky Way. Star clusters, HII regions and planetary nebulae, the interstellar medium, atomic and molecular clouds, dust. Stellar populations. Galactic structure, formation, dynamics. Galactic nuclei, bulges, disks, halo. Active Galactic Nuclei, supermassive black holes, quasars. Gravitational lens systems. The Milky Way and its contents",
            ),
    "astro-ph.HE": Category(
            id="astro-ph.HE",
            full_name="High Energy Astrophysical Phenomena",
            is_active=True,
            in_archive="astro-ph",
            is_general=False,
            description="Cosmic ray production, acceleration, propagation, detection. Gamma ray astronomy and bursts, X-rays, charged particles, supernovae and other explosive phenomena, stellar remnants and accretion systems, jets, microquasars, neutron stars, pulsars, black holes",
            ),
    "astro-ph.IM": Category(
            id="astro-ph.IM",
            full_name="Instrumentation and Methods for Astrophysics",
            is_active=True,
            in_archive="astro-ph",
            is_general=False,
            description="Detector and telescope design, experiment proposals. Laboratory Astrophysics. Methods for data analysis, statistical methods. Software, database design",
            ),
    "astro-ph.SR": Category(
            id="astro-ph.SR",
            full_name="Solar and Stellar Astrophysics",
            is_active=True,
            in_archive="astro-ph",
            is_general=False,
            description="White dwarfs, brown dwarfs, cataclysmic variables. Star formation and protostellar systems, stellar astrobiology, binary and multiple systems of stars, stellar evolution and structure, coronas. Central stars of planetary nebulae. Helioseismology, solar neutrinos, production and detection of gravitational radiation from stellar systems",
            ),
    "atom-ph": Category(
            id="atom-ph",
            full_name="Atomic, Molecular and Optical Physics",
            is_active=False,
            alt_name="physics.atom-ph",
            in_archive="atom-ph",
            is_general=False,
            ),
    "bayes-an": Category(
            id="bayes-an",
            full_name="Bayesian Analysis",
            is_active=False,
            alt_name="physics.data-an",
            in_archive="bayes-an",
            is_general=False,
            ),
    "chao-dyn": Category(
            id="chao-dyn",
            full_name="Chaotic Dynamics",
            is_active=False,
            alt_name="nlin.CD",
            in_archive="chao-dyn",
            is_general=False,
            ),
    "chem-ph": Category(
            id="chem-ph",
            full_name="Chemical Physics",
            is_active=False,
            alt_name="physics.chem-ph",
            in_archive="chem-ph",
            is_general=False,
            ),
    "cmp-lg": Category(
            id="cmp-lg",
            full_name="Computation and Language",
            alt_name="cs.CL",
            is_active=False,
            in_archive="cmp-lg",
            is_general=False,
            ),
    "comp-gas": Category(
            id="comp-gas",
            full_name="Cellular Automata and Lattice Gases",
            is_active=False,
            alt_name="nlin.CG",
            in_archive="comp-gas",
            is_general=False,
            ),
    "cond-mat": Category(
            id="cond-mat",
            full_name="Condensed Matter",
            is_active=False,
            in_archive="cond-mat",
            is_general=False,
            ),
    "cond-mat.dis-nn": Category(
            id="cond-mat.dis-nn",
            full_name="Disordered Systems and Neural Networks",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Glasses and spin glasses; properties of random, aperiodic and quasiperiodic systems; transport in disordered media; localization; phenomena mediated by defects and disorder; neural networks",
            ),
    "cond-mat.mes-hall": Category(
            id="cond-mat.mes-hall",
            full_name="Mesoscale and Nanoscale Physics",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Semiconducting nanostructures: quantum dots, wires, and wells. Single electronics, spintronics, 2d electron gases, quantum Hall effect, nanotubes, graphene, plasmonic nanostructures",
            ),
    "cond-mat.mtrl-sci": Category(
            id="cond-mat.mtrl-sci",
            full_name="Materials Science",
            is_active=True,
            alt_name="mtrl-th",
            in_archive="cond-mat",
            is_general=False,
            description="Techniques, synthesis, characterization, structure.  Structural phase transitions, mechanical properties, phonons. Defects, adsorbates, interfaces",
            ),
    "cond-mat.other": Category(
            id="cond-mat.other",
            full_name="Other Condensed Matter",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Work in condensed matter that does not fit into the other cond-mat classifications",
            ),
    "cond-mat.quant-gas": Category(
            id="cond-mat.quant-gas",
            full_name="Quantum Gases",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Ultracold atomic and molecular gases, Bose-Einstein condensation, Feshbach resonances, spinor condensates, optical lattices, quantum simulation with cold atoms and molecules, macroscopic interference phenomena",
            ),
    "cond-mat.soft": Category(
            id="cond-mat.soft",
            full_name="Soft Condensed Matter",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Membranes, polymers, liquid crystals, glasses, colloids, granular matter",
            ),
    "cond-mat.stat-mech": Category(
            id="cond-mat.stat-mech",
            full_name="Statistical Mechanics",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Phase transitions, thermodynamics, field theory, non-equilibrium phenomena, renormalization group and scaling, integrable models, turbulence",
            ),
    "cond-mat.str-el": Category(
            id="cond-mat.str-el",
            full_name="Strongly Correlated Electrons",
            is_active=True,
            in_archive="cond-mat",
            is_general=False,
            description="Quantum magnetism, non-Fermi liquids, spin liquids, quantum criticality, charge density waves, metal-insulator transitions",
            ),
    "cond-mat.supr-con": Category(
            id="cond-mat.supr-con",
            full_name="Superconductivity",
            is_active=True,
            alt_name="supr-con",
            in_archive="cond-mat",
            is_general=False,
            description="Superconductivity: theory, models, experiment.  Superflow in helium",
            ),
    "cs.AI": Category(
            id="cs.AI",
            full_name="Artificial Intelligence",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all areas of AI except Vision, Robotics, Machine Learning, Multiagent Systems, and Computation and Language (Natural Language Processing), which have separate subject areas. In particular, includes Expert Systems, Theorem Proving (although this may overlap with Logic in Computer Science), Knowledge Representation, Planning, and Uncertainty in AI. Roughly includes material in ACM Subject Classes I.2.0, I.2.1, I.2.3, I.2.4, I.2.8, and I.2.11.",
            ),
    "cs.AR": Category(
            id="cs.AR",
            full_name="Hardware Architecture",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers systems organization and hardware architecture. Roughly includes material in ACM Subject Classes C.0, C.1, and C.5.",
            ),
    "cs.CC": Category(
            id="cs.CC",
            full_name="Computational Complexity",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers models of computation, complexity classes, structural complexity, complexity tradeoffs, upper and lower bounds. Roughly includes material in ACM Subject Classes F.1 (computation by abstract devices), F.2.3 (tradeoffs among complexity measures), and F.4.3 (formal languages), although some material in formal languages may be more appropriate for Logic in Computer Science. Some material in F.2.1 and F.2.2, may also be appropriate here, but is more likely to have Data Structures and Algorithms as the primary subject area.",
            ),
    "cs.CE": Category(
            id="cs.CE",
            full_name="Computational Engineering, Finance, and Science",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers applications of computer science to the mathematical modeling of complex systems in the fields of science, engineering, and finance. Papers here are interdisciplinary and applications-oriented, focusing on techniques and tools that enable challenging computational simulations to be performed, for which the use of supercomputers or distributed computing platforms is often required. Includes material in ACM Subject Classes J.2, J.3, and J.4 (economics).",
            ),
    "cs.CG": Category(
            id="cs.CG",
            full_name="Computational Geometry",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Roughly includes material in ACM Subject Classes I.3.5 and F.2.2.",
            ),
    "cs.CL": Category(
            id="cs.CL",
            full_name="Computation and Language",
            is_active=True,
            alt_name="cmp-lg",
            in_archive="cs",
            is_general=False,
            description="Covers natural language processing. Roughly includes material in ACM Subject Class I.2.7. Note that work on artificial languages (programming languages, logics, formal systems) that does not explicitly address natural-language issues broadly construed (natural-language processing, computational linguistics, speech, text retrieval, etc.) is not appropriate for this area.",
            ),
    "cs.CR": Category(
            id="cs.CR",
            full_name="Cryptography and Security",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all areas of cryptography and security including authentication, public key cryptosytems, proof-carrying code, etc. Roughly includes material in ACM Subject Classes D.4.6 and E.3.",
            ),
    "cs.CV": Category(
            id="cs.CV",
            full_name="Computer Vision and Pattern Recognition",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers image processing, computer vision, pattern recognition, and scene understanding. Roughly includes material in ACM Subject Classes I.2.10, I.4, and I.5.",
            ),
    "cs.CY": Category(
            id="cs.CY",
            full_name="Computers and Society",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers impact of computers on society, computer ethics, information technology and public policy, legal aspects of computing, computers and education. Roughly includes material in ACM Subject Classes K.0, K.2, K.3, K.4, K.5, and K.7.",
            ),
    "cs.DB": Category(
            id="cs.DB",
            full_name="Databases",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers database management, datamining, and data processing. Roughly includes material in ACM Subject Classes E.2, E.5, H.0, H.2, and J.1.",
            ),
    "cs.DC": Category(
            id="cs.DC",
            full_name="Distributed, Parallel, and Cluster Computing",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers fault-tolerance, distributed algorithms, stabilility, parallel computation, and cluster computing. Roughly includes material in ACM Subject Classes C.1.2, C.1.4, C.2.4, D.1.3, D.4.5, D.4.7, E.1.",
            ),
    "cs.DL": Category(
            id="cs.DL",
            full_name="Digital Libraries",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all aspects of the digital library design and document and text creation. Note that there will be some overlap with Information Retrieval (which is a separate subject area). Roughly includes material in ACM Subject Classes H.3.5, H.3.6, H.3.7, I.7.",
            ),
    "cs.DM": Category(
            id="cs.DM",
            full_name="Discrete Mathematics",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers combinatorics, graph theory, applications of probability. Roughly includes material in ACM Subject Classes G.2 and G.3.",
            ),
    "cs.DS": Category(
            id="cs.DS",
            full_name="Data Structures and Algorithms",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers data structures and analysis of algorithms. Roughly includes material in ACM Subject Classes E.1, E.2, F.2.1, and F.2.2.",
            ),
    "cs.ET": Category(
            id="cs.ET",
            full_name="Emerging Technologies",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers approaches to information processing (computing, communication, sensing) and bio-chemical analysis based on alternatives to silicon CMOS-based technologies, such as nanoscale electronic, photonic, spin-based, superconducting, mechanical, bio-chemical and quantum technologies (this list is not exclusive). Topics of interest include (1) building blocks for emerging technologies, their scalability and adoption in larger systems, including integration with traditional technologies, (2) modeling, design and optimization of novel devices and systems, (3) models of computation, algorithm design and programming for emerging technologies.",
            ),
    "cs.FL": Category(
            id="cs.FL",
            full_name="Formal Languages and Automata Theory",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers automata theory, formal language theory, grammars, and combinatorics on words. This roughly corresponds to ACM Subject Classes F.1.1, and F.4.3. Papers dealing with computational complexity should go to cs.CC; papers dealing with logic should go to cs.LO.",
            ),
    "cs.GL": Category(
            id="cs.GL",
            full_name="General Literature",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers introductory material, survey material, predictions of future trends, biographies, and miscellaneous computer-science related material. Roughly includes all of ACM Subject Class A, except it does not include conference proceedings (which will be listed in the appropriate subject area).",
            ),
    "cs.GR": Category(
            id="cs.GR",
            full_name="Graphics",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all aspects of computer graphics. Roughly includes material in all of ACM Subject Class I.3, except that I.3.5 is is likely to have Computational Geometry as the primary subject area.",
            ),
    "cs.GT": Category(
            id="cs.GT",
            full_name="Computer Science and Game Theory",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all theoretical and applied aspects at the intersection of computer science and game theory, including work in mechanism design, learning in games (which may overlap with Learning), foundations of agent modeling in games (which may overlap with Multiagent systems), coordination, specification and formal methods for non-cooperative computational environments. The area also deals with applications of game theory to areas such as electronic commerce.",
            ),
    "cs.HC": Category(
            id="cs.HC",
            full_name="Human-Computer Interaction",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers human factors, user interfaces, and collaborative computing. Roughly includes material in ACM Subject Classes H.1.2 and all of H.5, except for H.5.1, which is more likely to have Multimedia as the primary subject area.",
            ),
    "cs.IR": Category(
            id="cs.IR",
            full_name="Information Retrieval",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers indexing, dictionaries, retrieval, content and analysis. Roughly includes material in ACM Subject Classes H.3.0, H.3.1, H.3.2, H.3.3, and H.3.4.",
            ),
    "cs.IT": Category(
            id="cs.IT",
            full_name="Information Theory",
            is_active=True,
            alt_name="math.IT",
            in_archive="cs",
            is_general=False,
            description="Covers theoretical and experimental aspects of information theory and coding. Includes material in ACM Subject Class E.4 and intersects with H.1.1.",
            ),
    "cs.LG": Category(
            id="cs.LG",
            full_name="Machine Learning",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Papers on all aspects of machine learning research (supervised, unsupervised, reinforcement learning, bandit problems, and so on) including also robustness, explanation, fairness, and methodology. cs.LG is also an appropriate primary category for applications of machine learning methods.",
            ),
    "cs.LO": Category(
            id="cs.LO",
            full_name="Logic in Computer Science",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all aspects of logic in computer science, including finite model theory, logics of programs, modal logic, and program verification. Programming language semantics should have Programming Languages as the primary subject area. Roughly includes material in ACM Subject Classes D.2.4, F.3.1, F.4.0, F.4.1, and F.4.2; some material in F.4.3 (formal languages) may also be appropriate here, although Computational Complexity is typically the more appropriate subject area.",
            ),
    "cs.MA": Category(
            id="cs.MA",
            full_name="Multiagent Systems",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers multiagent systems, distributed artificial intelligence, intelligent agents, coordinated interactions. and practical applications. Roughly covers ACM Subject Class I.2.11.",
            ),
    "cs.MM": Category(
            id="cs.MM",
            full_name="Multimedia",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Roughly includes material in ACM Subject Class H.5.1.",
            ),
    "cs.MS": Category(
            id="cs.MS",
            full_name="Mathematical Software",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Roughly includes material in ACM Subject Class G.4.",
            ),
    "cs.NA": Category(
            id="cs.NA",
            full_name="Numerical Analysis",
            is_active=True,
            alt_name="math.NA",
            in_archive="cs",
            is_general=False,
            description="cs.NA is an alias for math.NA. Roughly includes material in ACM Subject Class G.1.",
            ),
    "cs.NE": Category(
            id="cs.NE",
            full_name="Neural and Evolutionary Computing",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers neural networks, connectionism, genetic algorithms, artificial life, adaptive behavior. Roughly includes some material in ACM Subject Class C.1.3, I.2.6, I.5.",
            ),
    "cs.NI": Category(
            id="cs.NI",
            full_name="Networking and Internet Architecture",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all aspects of computer communication networks, including network architecture and design, network protocols, and internetwork standards (like TCP/IP). Also includes topics, such as web caching, that are directly relevant to Internet architecture and performance. Roughly includes all of ACM Subject Class C.2 except C.2.4, which is more likely to have Distributed, Parallel, and Cluster Computing as the primary subject area.",
            ),
    "cs.OH": Category(
            id="cs.OH",
            full_name="Other Computer Science",
            is_active=True,
            in_archive="cs",
            is_general=True,
            description="This is the classification to use for documents that do not fit anywhere else.",
            ),
    "cs.OS": Category(
            id="cs.OS",
            full_name="Operating Systems",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Roughly includes material in ACM Subject Classes D.4.1, D.4.2., D.4.3, D.4.4, D.4.5, D.4.7, and D.4.9.",
            ),
    "cs.PF": Category(
            id="cs.PF",
            full_name="Performance",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers performance measurement and evaluation, queueing, and simulation. Roughly includes material in ACM Subject Classes D.4.8 and K.6.2.",
            ),
    "cs.PL": Category(
            id="cs.PL",
            full_name="Programming Languages",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers programming language semantics, language features, programming approaches (such as object-oriented programming, functional programming, logic programming). Also includes material on compilers oriented towards programming languages; other material on compilers may be more appropriate in Architecture (AR). Roughly includes material in ACM Subject Classes D.1 and D.3.",
            ),
    "cs.RO": Category(
            id="cs.RO",
            full_name="Robotics",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Roughly includes material in ACM Subject Class I.2.9.",
            ),
    "cs.SC": Category(
            id="cs.SC",
            full_name="Symbolic Computation",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Roughly includes material in ACM Subject Class I.1.",
            ),
    "cs.SD": Category(
            id="cs.SD",
            full_name="Sound",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers all aspects of computing with sound, and sound as an information channel. Includes models of sound, analysis and synthesis, audio user interfaces, sonification of data, computer music, and sound signal processing. Includes ACM Subject Class H.5.5, and intersects with H.1.2, H.5.1, H.5.2, I.2.7, I.5.4, I.6.3, J.5, K.4.2.",
            ),
    "cs.SE": Category(
            id="cs.SE",
            full_name="Software Engineering",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers design tools, software metrics, testing and debugging, programming environments, etc. Roughly includes material in all of ACM Subject Classes D.2, except that D.2.4 (program verification) should probably have Logics in Computer Science as the primary subject area.",
            ),
    "cs.SI": Category(
            id="cs.SI",
            full_name="Social and Information Networks",
            is_active=True,
            in_archive="cs",
            is_general=False,
            description="Covers the design, analysis, and modeling of social and information networks, including their applications for on-line information access, communication, and interaction, and their roles as datasets in the exploration of questions in these and other domains, including connections to the social and biological sciences. Analysis and modeling of such networks includes topics in ACM Subject classes F.2, G.2, G.3, H.2, and I.2; applications in computing include topics in H.3, H.4, and H.5; and applications at the interface of computing and other disciplines include topics in J.1--J.7. Papers on computer communication systems and network protocols (e.g. TCP/IP) are generally a closer fit to the Networking and Internet Architecture (cs.NI) category.",
            ),
    "cs.SY": Category(
            id="cs.SY",
            full_name="Systems and Control",
            is_active=True,
            alt_name="eess.SY",
            in_archive="cs",
            is_general=False,
            description="cs.SY is an alias for eess.SY. This section includes theoretical and experimental research covering all facets of automatic control systems. The section is focused on methods of control system analysis and design using tools of modeling, simulation and optimization. Specific areas of research include nonlinear, distributed, adaptive, stochastic and robust control in addition to hybrid and discrete event systems. Application areas include automotive and aerospace control systems, network control, biological systems, multiagent and cooperative control, robotics, reinforcement learning, sensor networks, control of cyber-physical and energy-related systems, and control of computing systems.",
            ),
    "dg-ga": Category(
            id="dg-ga",
            full_name="Differential Geometry",
            is_active=False,
            alt_name="math.DG",
            in_archive="dg-ga",
            is_general=False,
            ),
    "econ.EM": Category(
            id="econ.EM",
            full_name="Econometrics",
            is_active=True,
            in_archive="econ",
            is_general=False,
            description="Econometric Theory, Micro-Econometrics, Macro-Econometrics, Empirical Content of Economic Relations discovered via New Methods, Methodological Aspects of the Application of Statistical Inference to Economic Data.",
            ),
    "econ.GN": Category(
            id="econ.GN",
            full_name="General Economics",
            is_active=True,
            alt_name="q-fin.EC",
            in_archive="econ",
            is_general=True,
            description="General methodological, applied, and empirical contributions to economics.",
            ),
    "econ.TH":Category(
            id="econ.TH",
            full_name="Theoretical Economics",
            is_active=True,
            in_archive="econ",
            is_general=False,
            description="Includes theoretical contributions to Contract Theory, Decision Theory, Game Theory, General Equilibrium, Growth, Learning and Evolution, Macroeconomics, Market and Mechanism Design, and Social Choice.",
            ),
    "eess.AS":Category(
            id="eess.AS",
            full_name="Audio and Speech Processing",
            is_active=True,
            in_archive="eess",
            is_general=False,
            description="Theory and methods for processing signals representing audio, speech, and language, and their applications. This includes analysis, synthesis, enhancement, transformation, classification and interpretation of such signals as well as the design, development, and evaluation of associated signal processing systems. Machine learning and pattern analysis applied to any of the above areas is also welcome.  Specific topics of interest include: auditory modeling and hearing aids; acoustic beamforming and source localization; classification of acoustic scenes; speaker separation; active noise control and echo cancellation; enhancement; de-reverberation; bioacoustics; music signals analysis, synthesis and modification; music information retrieval;  audio for multimedia and joint audio-video processing; spoken and written language modeling, segmentation, tagging, parsing, understanding, and translation; text mining; speech production, perception, and psychoacoustics; speech analysis, synthesis, and perceptual modeling and coding; robust speech recognition; speaker recognition and characterization; deep learning, online learning, and graphical models applied to speech, audio, and language signals; and implementation aspects ranging from system architecture to fast algorithms.",
            ),
    "eess.IV":Category(
            id="eess.IV",
            full_name="Image and Video Processing",
            is_active=True,
            in_archive="eess",
            is_general=False,
            description="Theory, algorithms, and architectures for the formation, capture, processing, communication, analysis, and display of images, video, and multidimensional signals in a wide variety of applications. Topics of interest include: mathematical, statistical, and perceptual image and video modeling and representation; linear and nonlinear filtering, de-blurring, enhancement, restoration, and reconstruction from degraded, low-resolution or tomographic data; lossless and lossy compression and coding; segmentation, alignment, and recognition; image rendering, visualization, and printing; computational imaging, including ultrasound, tomographic and magnetic resonance imaging; and image and video analysis, synthesis, storage, search and retrieval.",
            ),
    "eess.SP":Category(
            id="eess.SP",
            full_name="Signal Processing",
            is_active=True,
            in_archive="eess",
            is_general=False,
            description='Theory, algorithms, performance analysis and applications of signal and data analysis, including physical modeling, processing, detection and parameter estimation, learning, mining, retrieval, and information extraction. The term "signal" includes speech, audio, sonar, radar, geophysical, physiological, (bio-) medical, image, video, and multimodal natural and man-made signals, including communication signals and data. Topics of interest include: statistical signal processing, spectral estimation and system identification; filter design, adaptive filtering / stochastic learning; (compressive) sampling, sensing, and transform-domain methods including fast algorithms; signal processing for machine learning and machine learning for signal processing applications; in-network and graph signal processing; convex and nonconvex optimization methods for signal processing applications; radar, sonar, and sensor array beamforming and direction finding; communications signal processing; low power, multi-core and system-on-chip signal processing; sensing, communication, analysis and optimization for cyber-physical systems such as power grids and the Internet of Things.',
            ),
    "eess.SY":Category(
            id="eess.SY",
            full_name="Systems and Control",
            is_active=True,
            alt_name="cs.SY",
            in_archive="eess",
            is_general=False,
            description="This section includes theoretical and experimental research covering all facets of automatic control systems. The section is focused on methods of control system analysis and design using tools of modeling, simulation and optimization. Specific areas of research include nonlinear, distributed, adaptive, stochastic and robust control in addition to hybrid and discrete event systems. Application areas include automotive and aerospace control systems, network control, biological systems, multiagent and cooperative control, robotics, reinforcement learning, sensor networks, control of cyber-physical and energy-related systems, and control of computing systems.",
            ),
    "funct-an":Category(
            id="funct-an",
            full_name="Functional Analysis",
            is_active=False,
            alt_name="math.FA",
            in_archive="funct-an",
            is_general=False,
            ),
    "gr-qc":Category(
            id="gr-qc",
            full_name="General Relativity and Quantum Cosmology",
            is_active=True,
            in_archive="gr-qc",
            is_general=False,
            description="General Relativity and Quantum Cosmology Areas of gravitational physics, including experiments and observations related to the detection and interpretation of gravitational waves, experimental tests of gravitational theories, computational general relativity, relativistic astrophysics, solutions to Einstein's equations and their properties, alternative theories of gravity, classical and quantum cosmology, and quantum gravity.",
            ),
    "hep-ex":Category(
            id="hep-ex",
            full_name="High Energy Physics - Experiment",
            is_active=True,
            in_archive="hep-ex",
            is_general=False,
            description="Results from high-energy/particle physics experiments and prospects for future experimental results, including tests of the standard model, measurements of standard model parameters, searches for physics beyond the standard model, and astroparticle physics experimental results. Does not include: detectors and instrumentation nor analysis methods to conduct experiments.",
            ),
    "hep-lat":Category(
            id="hep-lat",
            full_name="High Energy Physics - Lattice",
            is_active=True,
            in_archive="hep-lat",
            is_general=False,
            description="Lattice field theory. Phenomenology from lattice field theory. Algorithms for lattice field theory.  Hardware for lattice field theory.",
            ),
    "hep-ph":Category(
            id="hep-ph",
            full_name="High Energy Physics - Phenomenology",
            is_active=True,
            in_archive="hep-ph",
            is_general=False,
            description="Theoretical particle physics and its interrelation with experiment. Prediction of particle physics observables: models, effective field theories, calculation techniques. Particle physics: analysis of theory through experimental results.",
            ),
    "hep-th":Category(
            id="hep-th",
            full_name="High Energy Physics - Theory",
            is_active=True,
            in_archive="hep-th",
            is_general=False,
            description="Formal aspects of quantum field theory. String theory, supersymmetry and supergravity.",
            ),
    "math-ph":Category(
            id="math-ph",
            full_name="Mathematical Physics",
            is_active=True,
            alt_name="math.MP",
            in_archive="math-ph",
            is_general=False,
            description="Articles in this category focus on areas of research that illustrate the application of mathematics to problems in physics, develop mathematical methods for such applications, or provide mathematically rigorous formulations of existing physical theories. Submissions to math-ph should be of interest to both physically oriented mathematicians and mathematically oriented physicists; submissions which are primarily of interest to theoretical physicists or to mathematicians should probably be directed to the respective physics/math categories",
            ),
    "math.AC":Category(
            id="math.AC",
            full_name="Commutative Algebra",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Commutative rings, modules, ideals, homological algebra, computational aspects, invariant theory, connections to algebraic geometry and combinatorics",
            ),
    "math.AG":Category(
            id="math.AG",
            full_name="Algebraic Geometry",
            is_active=True,
            alt_name="alg-geom",
            in_archive="math",
            is_general=False,
            description="Algebraic varieties, stacks, sheaves, schemes, moduli spaces, complex geometry, quantum cohomology",
            ),
    "math.AP":Category(
            id="math.AP",
            full_name="Analysis of PDEs",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Existence and uniqueness, boundary conditions, linear and non-linear operators, stability, soliton theory, integrable PDE's, conservation laws, qualitative dynamics",
            ),
    "math.AT":Category(
            id="math.AT",
            full_name="Algebraic Topology",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Homotopy theory, homological algebra, algebraic treatments of manifolds",
            ),
    "math.CA":Category(
            id="math.CA",
            full_name="Classical Analysis and ODEs",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Special functions, orthogonal polynomials, harmonic analysis, ODE's, differential relations, calculus of variations, approximations, expansions, asymptotics",
            ),
    "math.CO":Category(
            id="math.CO",
            full_name="Combinatorics",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Discrete mathematics, graph theory, enumeration, combinatorial optimization, Ramsey theory, combinatorial game theory",
            ),
    "math.CT":Category(
            id="math.CT",
            full_name="Category Theory",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Enriched categories, topoi, abelian categories, monoidal categories, homological algebra",
            ),
    "math.CV":Category(
            id="math.CV",
            full_name="Complex Variables",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Holomorphic functions, automorphic group actions and forms, pseudoconvexity, complex geometry, analytic spaces, analytic sheaves",
            ),
    "math.DG":Category(
            id="math.DG",
            full_name="Differential Geometry",
            is_active=True,
            alt_name="dg-ga",
            in_archive="math",
            is_general=False,
            description="Complex, contact, Riemannian, pseudo-Riemannian and Finsler geometry, relativity, gauge theory, global analysis",
            ),
    "math.DS":Category(
            id="math.DS",
            full_name="Dynamical Systems",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Dynamics of differential equations and flows, mechanics, classical few-body problems, iterations, complex dynamics, delayed differential equations",
            ),
    "math.FA":Category(
            id="math.FA",
            full_name="Functional Analysis",
            is_active=True,
            alt_name="funct-an",
            in_archive="math",
            is_general=False,
            description="Banach spaces, function spaces, real functions, integral transforms, theory of distributions, measure theory",
            ),
    "math.GM":Category(
            id="math.GM",
            full_name="General Mathematics",
            is_active=True,
            in_archive="math",
            is_general=True,
            description="Mathematical material of general interest, topics not covered elsewhere",
            ),
    "math.GN":Category(
            id="math.GN",
            full_name="General Topology",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Continuum theory, point-set topology, spaces with algebraic structure, foundations, dimension theory, local and global properties",
            ),
    "math.GR":Category(
            id="math.GR",
            full_name="Group Theory",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Finite groups, topological groups, representation theory, cohomology, classification and structure",
            ),
    "math.GT":Category(
            id="math.GT",
            full_name="Geometric Topology",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Manifolds, orbifolds, polyhedra, cell complexes, foliations, geometric structures",
            ),
    "math.HO":Category(
            id="math.HO",
            full_name="History and Overview",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Biographies, philosophy of mathematics, mathematics education, recreational mathematics, communication of mathematics, ethics in mathematics",
            ),
    "math.IT":Category(
            id="math.IT",
            full_name="Information Theory",
            is_active=True,
            alt_name="cs.IT",
            in_archive="math",
            is_general=False,
            description="math.IT is an alias for cs.IT. Covers theoretical and experimental aspects of information theory and coding.",
            ),
    "math.KT":Category(
            id="math.KT",
            full_name="K-Theory and Homology",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Algebraic and topological K-theory, relations with topology, commutative algebra, and operator algebras",
            ),
    "math.LO":Category(
            id="math.LO",
            full_name="Logic",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Logic, set theory, point-set topology, formal mathematics",
            ),
    "math.MG":Category(
            id="math.MG",
            full_name="Metric Geometry",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Euclidean, hyperbolic, discrete, convex, coarse geometry, comparisons in Riemannian geometry, symmetric spaces",
            ),
    "math.MP":Category(
            id="math.MP",
            full_name="Mathematical Physics",
            is_active=True,
            alt_name="math-ph",
            in_archive="math",
            is_general=False,
            description="math.MP is an alias for math-ph. Articles in this category focus on areas of research that illustrate the application of mathematics to problems in physics, develop mathematical methods for such applications, or provide mathematically rigorous formulations of existing physical theories. Submissions to math-ph should be of interest to both physically oriented mathematicians and mathematically oriented physicists; submissions which are primarily of interest to theoretical physicists or to mathematicians should probably be directed to the respective physics/math categories",
            ),
    "math.NA":Category(
            id="math.NA",
            full_name="Numerical Analysis",
            is_active=True,
            alt_name="cs.NA",
            in_archive="math",
            is_general=False,
            description="Numerical algorithms for problems in analysis and algebra, scientific computation",
            ),
    "math.NT":Category(
            id="math.NT",
            full_name="Number Theory",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Prime numbers, diophantine equations, analytic number theory, algebraic number theory, arithmetic geometry, Galois theory",
            ),
    "math.OA":Category(
            id="math.OA",
            full_name="Operator Algebras",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Algebras of operators on Hilbert space, C^*-algebras, von Neumann algebras, non-commutative geometry",
            ),
    "math.OC":Category(
            id="math.OC",
            full_name="Optimization and Control",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Operations research, linear programming, control theory, systems theory, optimal control, game theory",
            ),
    "math.PR":Category(
            id="math.PR",
            full_name="Probability",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Theory and applications of probability and stochastic processes: e.g. central limit theorems, large deviations, stochastic differential equations, models from statistical mechanics, queuing theory",
            ),
    "math.QA":Category(
            id="math.QA",
            full_name="Quantum Algebra",
            is_active=True,
            alt_name="q-alg",
            in_archive="math",
            is_general=False,
            description="Quantum groups, skein theories, operadic and diagrammatic algebra, quantum field theory",
            ),
    "math.RA":Category(
            id="math.RA",
            full_name="Rings and Algebras",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Non-commutative rings and algebras, non-associative algebras, universal algebra and lattice theory, linear algebra, semigroups",
            ),
    "math.RT":Category(
            id="math.RT",
            full_name="Representation Theory",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Linear representations of algebras and groups, Lie theory, associative algebras, multilinear algebra",
            ),
    "math.SG":Category(
            id="math.SG",
            full_name="Symplectic Geometry",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Hamiltonian systems, symplectic flows, classical integrable systems",
            ),
    "math.SP":Category(
            id="math.SP",
            full_name="Spectral Theory",
            is_active=True,
            in_archive="math",
            is_general=False,
            description="Schrodinger operators, operators on manifolds, general differential operators, numerical studies, integral operators, discrete models, resonances, non-self-adjoint operators, random operators/matrices",
            ),
    "math.ST":Category(
            id="math.ST",
            full_name="Statistics Theory",
            is_active=True,
            alt_name="stat.TH",
            in_archive="math",
            is_general=False,
            description="Applied, computational and theoretical statistics: e.g. statistical inference, regression, time series, multivariate analysis, data analysis, Markov chain Monte Carlo, design of experiments, case studies",
            ),
    "mtrl-th":Category(
            id="mtrl-th",
            full_name="Materials Theory",
            is_active=False,
            alt_name="cond-mat.mtrl-sci",
            in_archive="mtrl-th",
            is_general=False,
            ),
    "nlin.AO":Category(
            id="nlin.AO",
            full_name="Adaptation and Self-Organizing Systems",
            is_active=True,
            alt_name="adap-org",
            in_archive="nlin",
            is_general=False,
            description="Adaptation, self-organizing systems, statistical physics, fluctuating systems, stochastic processes, interacting particle systems, machine learning",
            ),
    "nlin.CD":Category(
            id="nlin.CD",
            full_name="Chaotic Dynamics",
            is_active=True,
            alt_name="chao-dyn",
            in_archive="nlin",
            is_general=False,
            description="Dynamical systems, chaos, quantum chaos, topological dynamics, cycle expansions, turbulence, propagation",
            ),
    "nlin.CG":Category(
            id="nlin.CG",
            full_name="Cellular Automata and Lattice Gases",
            is_active=True,
            alt_name="comp-gas",
            in_archive="nlin",
            is_general=False,
            description="Computational methods, time series analysis, signal processing, wavelets, lattice gases",
            ),
    "nlin.PS":Category(
            id="nlin.PS",
            full_name="Pattern Formation and Solitons",
            is_active=True,
            alt_name="patt-sol",
            in_archive="nlin",
            is_general=False,
            description="Pattern formation, coherent structures, solitons",
            ),
    "nlin.SI":Category(
            id="nlin.SI",
            full_name="Exactly Solvable and Integrable Systems",
            is_active=True,
            alt_name="solv-int",
            in_archive="nlin",
            is_general=False,
            description="Exactly solvable systems, integrable PDEs, integrable ODEs, Painleve analysis, integrable discrete maps, solvable lattice models, integrable quantum systems",
            ),
    "nucl-ex":Category(
            id="nucl-ex",
            full_name="Nuclear Experiment",
            is_active=True,
            in_archive="nucl-ex",
            is_general=False,
            description="Nuclear Experiment Results from experimental nuclear physics including the areas of fundamental interactions, measurements at low- and medium-energy, as well as relativistic heavy-ion collisions.  Does not include: detectors and instrumentation nor analysis methods to conduct experiments; descriptions of experimental programs (present or future); comments on published results",
            ),
    "nucl-th":Category(
            id="nucl-th",
            full_name="Nuclear Theory",
            is_active=True,
            in_archive="nucl-th",
            is_general=False,
            description="Nuclear Theory Theory of nuclear structure covering wide area from models of hadron structure to neutron stars. Nuclear equation of states at different external conditions. Theory of nuclear reactions including heavy-ion reactions at low and high energies. It does not include problems of data analysis, physics of nuclear reactors, problems of safety, reactor construction",
            ),
    "patt-sol":Category(
            id="patt-sol",
            full_name="Pattern Formation and Solitons",
            is_active=False,
            alt_name="nlin.PS",
            in_archive="patt-sol",
            is_general=False,
            ),
    "physics.acc-ph":Category(
            id="physics.acc-ph",
            full_name="Accelerator Physics",
            is_active=True,
            alt_name="acc-phys",
            in_archive="physics",
            is_general=False,
            description="Accelerator theory and simulation. Accelerator technology. Accelerator experiments. Beam Physics. Accelerator design and optimization. Advanced accelerator concepts. Radiation sources including synchrotron light sources and free electron lasers. Applications of accelerators.",
            ),
    "physics.ao-ph":Category(
            id="physics.ao-ph",
            full_name="Atmospheric and Oceanic Physics",
            is_active=True,
            alt_name="ao-sci",
            in_archive="physics",
            is_general=False,
            description="Atmospheric and oceanic physics and physical chemistry, biogeophysics, and climate science",
            ),
    "physics.app-ph":Category(
            id="physics.app-ph",
            full_name="Applied Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Applications of physics to new technology, including electronic devices, optics, photonics, microwaves, spintronics, advanced materials, metamaterials, nanotechnology, and energy sciences.",
            ),
    "physics.atm-clus":Category(
            id="physics.atm-clus",
            full_name="Atomic and Molecular Clusters",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Atomic and molecular clusters, nanoparticles: geometric, electronic, optical, chemical, magnetic properties, shell structure, phase transitions, optical spectroscopy, mass spectrometry, photoelectron spectroscopy, ionization potential, electron affinity, interaction with intense light pulses, electron diffraction, light scattering, ab initio calculations, DFT theory, fragmentation, Coulomb explosion, hydrodynamic expansion.",
            ),
    "physics.atom-ph":Category(
            id="physics.atom-ph",
            full_name="Atomic Physics",
            is_active=True,
            alt_name="atom-ph",
            in_archive="physics",
            is_general=False,
            description="Atomic and molecular structure, spectra, collisions, and data. Atoms and molecules in external fields. Molecular dynamics and coherent and optical control. Cold atoms and molecules. Cold collisions. Optical lattices.",
            ),
    "physics.bio-ph":Category(
            id="physics.bio-ph",
            full_name="Biological Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Molecular biophysics, cellular biophysics, neurological biophysics, membrane biophysics, single-molecule biophysics, ecological biophysics, quantum phenomena in biological systems (quantum biophysics), theoretical biophysics, molecular dynamics/modeling and simulation, game theory, biomechanics, bioinformatics, microorganisms, virology, evolution, biophysical methods.",
            ),
    "physics.chem-ph":Category(
            id="physics.chem-ph",
            full_name="Chemical Physics",
            is_active=True,
            alt_name="chem-ph",
            in_archive="physics",
            is_general=False,
            description="Experimental, computational, and theoretical physics of atoms, molecules, and clusters - Classical and quantum description of states, processes, and dynamics; spectroscopy, electronic structure, conformations, reactions, interactions, and phases. Chemical thermodynamics. Disperse systems. High pressure chemistry. Solid state chemistry. Surface and interface chemistry.",
            ),
    "physics.class-ph":Category(
            id="physics.class-ph",
            full_name="Classical Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Newtonian and relativistic dynamics; many particle systems; planetary motions; chaos in classical dynamics. Maxwell's  equations and  dynamics of charged systems and  electromagnetic forces in materials. Vibrating systems such as membranes and cantilevers; optomechanics. Classical waves, including acoustics and elasticity; physics of music and musical instruments. Classical thermodynamics and  heat flow problems.",
            ),
    "physics.comp-ph":Category(
            id="physics.comp-ph",
            full_name="Computational Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="All aspects of computational science applied to physics.",
            ),
    "physics.data-an":Category(
            id="physics.data-an",
            full_name="Data Analysis, Statistics and Probability",
            is_active=True,
            alt_name="bayes-an",
            in_archive="physics",
            is_general=False,
            description="Methods, software and hardware for physics data analysis: data processing and storage; measurement methodology; statistical and mathematical aspects such as parametrization and uncertainties.",
            ),
    "physics.ed-ph":Category(
            id="physics.ed-ph",
            full_name="Physics Education",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Report of results of a research study, laboratory experience, assessment or classroom practice that represents a way to improve teaching and learning in physics. Also, report on misconceptions of students, textbook errors, and other similar information relative to promoting physics understanding.",
            ),
    "physics.flu-dyn":Category(
            id="physics.flu-dyn",
            full_name="Fluid Dynamics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Turbulence, instabilities, incompressible/compressible flows, reacting flows. Aero/hydrodynamics, fluid-structure interactions, acoustics. Biological fluid dynamics, micro/nanofluidics, interfacial phenomena. Complex fluids, suspensions and granular flows, porous media flows. Geophysical flows, thermoconvective and stratified flows. Mathematical and computational methods for fluid dynamics, fluid flow models, experimental techniques.",
            ),
    "physics.gen-ph":Category(
            id="physics.gen-ph",
            full_name="General Physics",
            is_active=True,
            in_archive="physics",
            is_general=True,
            ),
    "physics.geo-ph":Category(
            id="physics.geo-ph",
            full_name="Geophysics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Atmospheric physics. Biogeosciences. Computational geophysics. Geographic location. Geoinformatics. Geophysical techniques. Hydrospheric geophysics. Magnetospheric physics. Mathematical geophysics. Planetology. Solar system. Solid earth geophysics. Space plasma physics. Mineral physics. High pressure physics.",
            ),
    "physics.hist-ph":Category(
            id="physics.hist-ph",
            full_name="History and Philosophy of Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="History and philosophy of all branches of physics, astrophysics, and cosmology, including appreciations of physicists.",
            ),
    "physics.ins-det":Category(
            id="physics.ins-det",
            full_name="Instrumentation and Detectors",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Instrumentation and Detectors for research in natural science, including optical, molecular, atomic, nuclear and particle physics instrumentation and the associated electronics, services, infrastructure and control equipment. ",
            ),
    "physics.med-ph":Category(
            id="physics.med-ph",
            full_name="Medical Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Radiation therapy. Radiation dosimetry. Biomedical imaging modelling.  Reconstruction, processing, and analysis. Biomedical system modelling and analysis. Health physics. New imaging or therapy modalities.",
            ),
    "physics.optics":Category(
            id="physics.optics",
            full_name="Optics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Adaptive optics. Astronomical optics. Atmospheric optics. Biomedical optics. Cardinal points. Collimation. Doppler effect. Fiber optics. Fourier optics. Geometrical optics (Gradient index optics. Holography. Infrared optics. Integrated optics. Laser applications. Laser optical systems. Lasers. Light amplification. Light diffraction. Luminescence. Microoptics. Nano optics. Ocean optics. Optical computing. Optical devices. Optical imaging. Optical materials. Optical metrology. Optical microscopy. Optical properties. Optical signal processing. Optical testing techniques. Optical wave propagation. Paraxial optics. Photoabsorption. Photoexcitations. Physical optics. Physiological optics. Quantum optics. Segmented optics. Spectra. Statistical optics. Surface optics. Ultrafast optics. Wave optics. X-ray optics.",
            ),
    "physics.plasm-ph":Category(
            id="physics.plasm-ph",
            full_name="Plasma Physics",
            is_active=True,
            alt_name="plasm-ph",
            in_archive="physics",
            is_general=False,
            description="Fundamental plasma physics. Magnetically Confined Plasmas (includes magnetic fusion energy research). High Energy Density Plasmas (inertial confinement plasmas, laser-plasma interactions). Ionospheric, Heliophysical, and Astrophysical plasmas (includes sun and solar system plasmas). Lasers, Accelerators, and Radiation Generation. Low temperature plasmas and plasma applications (include dusty plasmas, semiconductor etching, plasma-based nanotechnology, medical applications). Plasma Diagnostics, Engineering and Enabling Technologies (includes fusion reactor design, heating systems, diagnostics, experimental techniques)",
            ),
    "physics.pop-ph":Category(
            id="physics.pop-ph",
            full_name="Popular Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            ),
    "physics.soc-ph":Category(
            id="physics.soc-ph",
            full_name="Physics and Society",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Structure, dynamics and collective behavior of societies and groups (human or otherwise). Quantitative analysis of social networks and other complex networks. Physics and engineering of infrastructure and systems of broad societal impact (e.g., energy grids, transportation networks).",
            ),
    "physics.space-ph":Category(
            id="physics.space-ph",
            full_name="Space Physics",
            is_active=True,
            in_archive="physics",
            is_general=False,
            description="Space plasma physics. Heliophysics. Space weather. Planetary magnetospheres, ionospheres and magnetotail. Auroras. Interplanetary space. Cosmic rays. Synchrotron radiation. Radio astronomy.",
            ),
    "plasm-ph":Category(
            id="plasm-ph",
            full_name="Plasma Physics",
            is_active=False,
            alt_name="physics.plasm-ph",
            in_archive="plasm-ph",
            is_general=False,
            ),
    "q-alg":Category(
            id="q-alg",
            full_name="Quantum Algebra and Topology",
            is_active=False,
            alt_name="math.QA",
            in_archive="q-alg",
            is_general=False,
            ),
    "q-bio":Category(
            id="q-bio",
            full_name="Quantitative Biology",
            is_active=False,
            in_archive="q-bio",
            is_general=False,
            ),
    "q-bio.BM":Category(
            id="q-bio.BM",
            full_name="Biomolecules",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="DNA, RNA, proteins, lipids, etc.; molecular structures and folding kinetics; molecular interactions; single-molecule manipulation.",
            ),
    "q-bio.CB":Category(
            id="q-bio.CB",
            full_name="Cell Behavior",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="Cell-cell signaling and interaction; morphogenesis and development; apoptosis; bacterial conjugation; viral-host interaction; immunology",
            ),
    "q-bio.GN":Category(
            id="q-bio.GN",
            full_name="Genomics",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="DNA sequencing and assembly; gene and motif finding; RNA editing and alternative splicing; genomic structure and processes (replication, transcription, methylation, etc); mutational processes.",
            ),
    "q-bio.MN":Category(
            id="q-bio.MN",
            full_name="Molecular Networks",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="Gene regulation, signal transduction, proteomics, metabolomics, gene and enzymatic networks",
            ),
    "q-bio.NC":Category(
            id="q-bio.NC",
            full_name="Neurons and Cognition",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="Synapse, cortex, neuronal dynamics, neural network, sensorimotor control, behavior, attention",
            ),
    "q-bio.OT":Category(
            id="q-bio.OT",
            full_name="Other Quantitative Biology",
            is_active=True,
            in_archive="q-bio",
            is_general=True,
            description="Work in quantitative biology that does not fit into the other q-bio classifications",
            ),
    "q-bio.PE":Category(
            id="q-bio.PE",
            full_name="Populations and Evolution",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="Population dynamics, spatio-temporal and epidemiological models, dynamic speciation, co-evolution, biodiversity, foodwebs, aging; molecular evolution and phylogeny; directed evolution; origin of life",
            ),
    "q-bio.QM":Category(
            id="q-bio.QM",
            full_name="Quantitative Methods",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="All experimental, numerical, statistical and mathematical contributions of value to biology",
            ),
    "q-bio.SC":Category(
            id="q-bio.SC",
            full_name="Subcellular Processes",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="Assembly and control of subcellular structures (channels, organelles, cytoskeletons, capsules, etc.); molecular motors, transport, subcellular localization; mitosis and meiosis",
            ),
    "q-bio.TO":Category(
            id="q-bio.TO",
            full_name="Tissues and Organs",
            is_active=True,
            in_archive="q-bio",
            is_general=False,
            description="Blood flow in vessels, biomechanics of bones, electrical waves, endocrine system, tumor growth",
            ),
    "q-fin.CP":Category(
            id="q-fin.CP",
            full_name="Computational Finance",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Computational methods, including Monte Carlo, PDE, lattice and other numerical methods with applications to financial modeling",
            ),
    "q-fin.EC":Category(
            id="q-fin.EC",
            full_name="Economics",
            is_active=True,
            alt_name="econ.GN",
            in_archive="q-fin",
            is_general=False,
            description="q-fin.EC is an alias for econ.GN. Economics, including micro and macro economics, international economics, theory of the firm, labor economics, and other economic topics outside finance",
            ),
    "q-fin.GN":Category(
            id="q-fin.GN",
            full_name="General Finance",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Development of general quantitative methodologies with applications in finance",
            ),
    "q-fin.MF":Category(
            id="q-fin.MF",
            full_name="Mathematical Finance",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Mathematical and analytical methods of finance, including stochastic, probabilistic and functional analysis, algebraic, geometric and other methods",
            ),
    "q-fin.PM":Category(
            id="q-fin.PM",
            full_name="Portfolio Management",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Security selection and optimization, capital allocation, investment strategies and performance measurement",
            ),
    "q-fin.PR":Category(
            id="q-fin.PR",
            full_name="Pricing of Securities",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Valuation and hedging of financial securities, their derivatives, and structured products",
            ),
    "q-fin.RM":Category(
            id="q-fin.RM",
            full_name="Risk Management",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Measurement and management of financial risks in trading, banking, insurance, corporate and other applications",
            ),
    "q-fin.ST":Category(
            id="q-fin.ST",
            full_name="Statistical Finance",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Statistical, econometric and econophysics analyses with applications to financial markets and economic data",
            ),
    "q-fin.TR":Category(
            id="q-fin.TR",
            full_name="Trading and Market Microstructure",
            is_active=True,
            in_archive="q-fin",
            is_general=False,
            description="Market microstructure, liquidity, exchange and auction design, automated trading, agent-based modeling and market-making",
            ),
    "quant-ph":Category(
            id="quant-ph",
            full_name="Quantum Physics",
            is_active=True,
            in_archive="quant-ph",
            is_general=False,
            ),
    "solv-int":Category(
            id="solv-int",
            full_name="Exactly Solvable and Integrable Systems",
            is_active=False,
            alt_name="nlin.SI",
            in_archive="solv-int",
            is_general=False,
            ),
    "stat.AP":Category(
            id="stat.AP",
            full_name="Applications",
            is_active=True,
            in_archive="stat",
            is_general=False,
            description="Biology, Education, Epidemiology, Engineering, Environmental Sciences, Medical, Physical Sciences, Quality Control, Social Sciences",
            ),
    "stat.CO":Category(
            id="stat.CO",
            full_name="Computation",
            is_active=True,
            in_archive="stat",
            is_general=False,
            description="Algorithms, Simulation, Visualization",
            ),
    "stat.ME":Category(
            id="stat.ME",
            full_name="Methodology",
            is_active=True,
            in_archive="stat",
            is_general=False,
            description="Design, Surveys, Model Selection, Multiple Testing, Multivariate Methods, Signal and Image Processing, Time Series, Smoothing, Spatial Statistics, Survival Analysis, Nonparametric and Semiparametric Methods",
            ),
    "stat.ML":Category(
            id="stat.ML",
            full_name="Machine Learning",
            is_active=True,
            in_archive="stat",
            is_general=False,
            description="Covers machine learning papers (supervised, unsupervised, semi-supervised learning, graphical models, reinforcement learning, bandits, high dimensional inference, etc.) with a statistical or theoretical grounding",
            ),
    "stat.OT":Category(
            id="stat.OT",
            full_name="Other Statistics",
            is_active=True,
            in_archive="stat",
            is_general=False,
            description="Work in statistics that does not fit into the other stat classifications",
            ),
    "stat.TH":Category(
            id="stat.TH",
            full_name="Statistics Theory",
            is_active=True,
            alt_name="math.ST",
            in_archive="stat",
            is_general=False,
            description="stat.TH is an alias for math.ST. Asymptotics, Bayesian Inference, Decision Theory, Estimation, Foundations, Inference, Testing.",
            ),
    "supr-con":Category(
            id="supr-con",
            full_name="Superconductivity",
            is_active=False,
            alt_name="cond-mat.supr-con",
            in_archive="supr-con",
            is_general=False,
            ),
    "test":Category(
            id="test",
            full_name="Test",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.dis-nn":Category(
            id="test.dis-nn",
            full_name="Test Disruptive Networks",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.mes-hall":Category(
            id="test.mes-hall",
            full_name="Test Hall",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.mtrl-sci":Category(
            id="test.mtrl-sci",
            full_name="Test Mtrl-Sci",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.soft":Category(
            id="test.soft",
            full_name="Test Soft",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.stat-mech":Category(
            id="test.stat-mech",
            full_name="Test Mechanics",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.str-el":Category(
            id="test.str-el",
            full_name="Test Electrons",
            is_active=False,
            in_archive="test",
            is_general=False,
            ),
    "test.supr-con":Category(
            id="test.supr-con",
            full_name="Test Superconductivity",
            is_active=False,
            in_archive="test",
            is_general=False,
            )
}

CATEGORIES_ACTIVE = {key: cat for key, cat in CATEGORIES.items()
                     if cat.is_active}

CATEGORY_ALIASES = {
    'math.MP': 'math-ph',
    'stat.TH': 'math.ST',
    'math.IT': 'cs.IT',
    'q-fin.EC': 'econ.GN',
    'cs.SY': 'eess.SY',
    'cs.NA': 'math.NA'
}
"""
Equivalences: category alias: canonical category
The name on the right is considered the canonical one
This model is based on the notion that only two categories may be
equivalent--not more. There would have to be some significant changes
to the (classic) code to support three-way equivalences, this code could upgrade to a list of alternate names.
"""
