"""Generic checks package: exposes all generic checks."""

from qa.checks.generic.text import (  # noqa
    AllBracketsBalanced,
    ContainsDigits,
    ContainsLetters,
    DoesNotBeginWithAbstract,
    DoesNotBeginWithAuthor,
    DoesNotBeginWithTitle,
    DoesNotContainAccepted,
    DoesNotContainAnonymous,
    DoesNotContainBadDoiPrefix,
    DoesNotContainBareDoi,
    DoesNotContainBibtex,
    DoesNotContainControlChars,
    DoesNotContainControlCharsAllowNewlines,
    DoesNotContainCorresponding,
    DoesNotContainDoi,
    DoesNotContainLinebreak,
    DoesNotContainSemicolon,
    DoesNotContainSubmitted,
    DoesNotContainTex,
    DoesNotContainTexBeginEnv,
    DoesNotContainTexDagger,
    DoesNotContainTildeAsHardSpace,
    DoesNotContainUnnecessaryEscape,
    DoesNotContainUrl,
    DoesNotEndWithPunctuation,
    DoesNotStartWithLowercase,
    DoiHasValidFormat,
    NoAnnotationSymbols,
    NoBoundaryWhitespace,
    NoExcessiveCapitals,
    NoExtraWhitespace,
    NoHtmlElements,
    NoUnapprovedLongCapsWords,
    NoUnnecessarySpaceInParens,
    NoUtf8DecodingErrors,
    NotTooLong,
    NotTooShort,
)

from qa.checks.generic.author_name import (  # noqa
    AuthorNamesDoNotContainAffiliation,
    AuthorNamesDoNotContainBrackets,
    AuthorNamesDoNotContainNumbers,
    AuthorNamesDoNotContainSemicolon,
    AuthorsDoNotContainLlmAuthor,
    AuthorsDoNotContainLoneSurname,
)
