name: Run Python Tests
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          pip --version
          poetry --version
          # Check if poetry lock file is current with pyproject.toml
          poetry check --lock
          poetry install --with=dev
      - name: Run Tests
        run: poetry run pytest --cov=arxiv fourohfour --cov-fail-under=36 arxiv fourohfour
      # - name: Check Types
      # TODO The types are in bad shape and need to be fixed
      #   run: poetry run mypy --exclude "test*" -p arxiv
      - name: Check Doc Style
        run: poetry run pydocstyle --convention=numpy --add-ignore=D401 arxiv
      - name: Run App Tests
        run: poetry run python tests/run_app_tests.py
