name: Run Python Tests
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt install -y protobuf-compiler
          protoc --version        
          python -m pip install --upgrade pip
          python -m pip install poetry
          pip --version
          poetry --version
          # Check if poetry lock file is current with pyproject.toml
          poetry check --lock
          poetry install --with=dev --no-ansi

      - name: Run db/test with MySQL docker
        run: |
          sudo apt update
          sudo apt install -y mysql-client
          cd arxiv && poetry run pytest auth/legacy/tests --db=mysql

      - name: Run arxiv-base tests with coverage
        run: poetry run pytest --cov=arxiv.base fourohfour --cov-fail-under=75 arxiv/base fourohfour
      # - name: Check Types
      # TODO The types are in bad shape and need to be fixed
      #   run: poetry run mypy --exclude "test*" -p arxiv

      - name: Install Firefox ESR and test driver
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt update
          sudo apt install -y firefox-esr
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.35.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.35.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run other tests
        # These tests are split out because their coverage is low
        run: poetry run pytest --cov=arxiv --cov-fail-under=40 arxiv --ignore=arxiv/base --ignore=arxiv/auth/legacy --db=sqlite
      #- name: Check Doc Style
      #  run: poetry run pydocstyle --convention=numpy --add-ignore=D401 arxiv

      - name: Run App Tests
        run: poetry run python tests/run_app_tests.py

