name: Run Python Tests
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7.20
        ports:
          - 23306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          pip --version
          poetry --version
          # Check if poetry lock file is current with pyproject.toml
          poetry check --lock
          poetry install --quiet --with=dev 

      - name: Load db schema
        run: |
          sudo apt update
          sudo apt install -y mysql-client
          poetry run python development/load_arxiv_db_schema.py --db_name=testdb --db_port=23306 --root_password=rootpassword --schema=development/arxiv_db_schema.sql

      - name: Run arxiv-base tests with coverage
        run: poetry run pytest --cov=arxiv.base fourohfour --cov-fail-under=67 arxiv/base fourohfour
      # - name: Check Types
      # TODO The types are in bad shape and need to be fixed
      #   run: poetry run mypy --exclude "test*" -p arxiv

      # It needs to be non-Snap binary and thus it's from Mozilla PPA.
      - name: Install Firefox ESR, test driver, mysqladmin
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt update
          sudo apt install -y firefox-esr mysql-client-core-8.0
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.35.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.35.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run other tests
        run: poetry run pytest --cov=arxiv --cov-fail-under=25 arxiv

      #- name: Check Doc Style
      #  run: poetry run pydocstyle --convention=numpy --add-ignore=D401 arxiv

      - name: Run App Tests
        run: poetry run python tests/run_app_tests.py
